### ISSUE TITLE
docker-compose -f docker/docker-compose.yml exec php phing demo

### ISSUE THREAD

**Issue by stanley87** [DivanteLtd/open-loyalty#113]
my side hitting error after running docker command show as below:

Nothing to update - your database is already in sync with the current entity metadata.
Dropped Broadway event-store schema
Created Broadway event-store schema
08:35:54 ERROR     [console] Error thrown while running command "doctrine:fixtures:load --fixtures 'src/OpenLoyalty/Bundle/DemoBundle/_DataFixtures/ORM/' -n". Message: "Could not find any fixtures to load in:

- src/OpenLoyalty/Bundle/DemoBundle/_DataFixtures/ORM/" ["error" => InvalidArgumentException { …},"command" => "doctrine:fixtures:load --fixtures 'src/OpenLoyalty/Bundle/DemoBundle/_DataFixtures/ORM/' -n","message" => """  Could not find any fixtures to load in: \n  \n  - src/OpenLoyalty/Bundle/DemoBundle/_DataFixtures/ORM/  """] []

In LoadDataFixturesDoctrineCommand.php line 108:

  Could not find any fixtures to load in:

  - src/OpenLoyalty/Bundle/DemoBundle/_DataFixtures/ORM/

doctrine:fixtures:load [--fixtures [FIXTURES]] [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [--multiple-transactions] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

BUILD FAILED
/var/www/openloyalty/build.xml:69:43: Task exited with code 1

**Comment by stanley87** [comment]
closed the issue,solution existed in existing closed issue

**Comment by stanley87** [comment]
reopen due to same issue still exist,
using the latest zip
using windows 10
using vagrant install steps

**Comment by ShahabKhalid** [comment]
Facing same issue!

**Comment by eligiable** [comment]
Any Fix for the above, I'm getting the following error on Ubuntu 16:

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
Creating network "docker_default" with the default driver
Building elk
Step 1/2 : FROM elasticsearch:2.2
2.2: Pulling from library/elasticsearch
386a066cd84a: Pull complete
75ea84187083: Pull complete
3e2e387eb26a: Pull complete
eef540699244: Pull complete
1624a2f8d114: Pull complete
7018f4ec6e0a: Pull complete
6ca3bc2ad3b3: Pull complete
424638b495a6: Pull complete
2ff72d0b7bea: Pull complete
9d25542ccc02: Pull complete
7764c111a5c7: Pull complete
a076ea41b544: Pull complete
4841e9c2a909: Pull complete
ed491141ede1: Pull complete
Digest: sha256:c243ff1ee18aed0680dcbe0abaeacdbf59fa6b35a2a902262787f841de6d7b88
Status: Downloaded newer image for elasticsearch:2.2
 ---> c3f0d8455a2f
Step 2/2 : RUN echo "index.max_result_window: 5000000" >> /usr/share/elasticsearch/config/elasticsearch.yml
 ---> Running in 528f946c73c3
 ---> d04ad82f8cb5
Removing intermediate container 528f946c73c3
Successfully built d04ad82f8cb5
WARNING: Image for service elk was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building frontend
Step 1/6 : FROM divante/open-loyalty-base-nodejs AS front
ERROR: Service 'frontend' failed to build: Error parsing reference: "divante/open-loyalty-base-nodejs AS front" is not a valid repository/tag: invalid reference format

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
Building elk
Step 1/2 : FROM elasticsearch:2.2
 ---> c3f0d8455a2f
Step 2/2 : RUN echo "index.max_result_window: 5000000" >> /usr/share/elasticsearch/config/elasticsearch.yml
 ---> Using cache
 ---> d04ad82f8cb5
Successfully built d04ad82f8cb5
Building frontend
Step 1/6 : FROM divante/open-loyalty-base-nodejs AS front
ERROR: Service 'frontend' failed to build: Error parsing reference: "divante/open-loyalty-base-nodejs AS front" is not a valid repository/tag: invalid reference format

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.

**Comment by pokono** [comment]
> closed the issue,solution existed in existing closed issue

Which one is the issue? Facing the same problem.
