### ISSUE TITLE
Application work incorrectly after change domain name. 

### ISSUE THREAD

**Issue by tahuyhien** [DivanteLtd/open-loyalty#133]
Hi team,
i follow file 'how_to_change_domain.rst' to change domain name then run 'docker-compose up' . After i change domain to my custom then application run incorrectly as below

--

here is my docker file: 

--
Please correct me if anything wrong

**Comment by tjurczak** [comment]
Hi,

I think that domain has been changed correctly, because developer console shows that your requests are sent to openloyalty.acb.itc, but openloylaty on this instance returns credentials error, so i suppose that this instance is empty (without data). Try to load some data using `phing setup` or `phing basic-setup`
