### ISSUE TITLE
"docker-compose backend setup" command issue

### ISSUE THREAD

**Issue by vikrantkjain** [DivanteLtd/open-loyalty#48]
Hi Guys,
I am getting following error when executing  "docker-compose exec backend phing setup" command

[Doctrine\DBAL\Exception\InvalidFieldNameException]
  An exception occurred while executing 'SELECT min_value, increment_by FROM "ol__roles_id_seq"':
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "ol__roles_id_seq"
             ^
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "ol__roles_id_seq"
                 ^
  [PDOException]
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
  LINE 1: SELECT min_value, increment_by FROM "ol__roles_id_seq"

I have executed this command after "docker-compose up" .
Please check the issue and let me know if I am missing anything.
Thanks

**Comment by colejarczyk** [comment]
Hi @vikrantkjain 

Guys from Postgres released version 10 recently on the docker hub and marked it as latest. As you probably know, we're using Doctrine for the persistence layer and Doctrine doesn't fully support Postgres 10 yet. This bug is already reported here https://github.com/doctrine/dbal/issues/2868

We resolved this issue in version 1.3.0 just by changing in docker-compose "postgres:latest" to "postgres:9".
