### ISSUE TITLE
 transactionID vs transactionDocumentNumber ?

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#76]
What is the difference between _transactionID_ and _transactionDocumentNumber_ ?

When I assign a transaction to a customer **(POST /api/admin/transaction/customer/assign)**, I realized that in the api, I have to use _documentNumber_ (_transactionDocumentNumber_), instead of _transactionID_.  

First, I send a request to create a transaction (api/transaction). After that, I assign the transaction's _documentNumber_ for a customer. The first time it's ok. I try assign the second time, it pop up an error : "Customer is already assign to this transaction". Ok, It makes sense, 1 _documentNumber_ can only be assigned to 1 customer. 

However, when I send the same request to re-create the transaction, with exactly the same _documentNumber_ . It's still created. I wonder why ? 

I try to assign  the _documentNumber_ for the customer again, and it works (after re-creating the transaction). 

It's quite confused because I can create a lot of transactions with exactly the same _documentNumber_. And even more when I assign them to customers. 

Why  dont we use _transactionID_ instead to identify a transaction when assigning it to a customer ? 
Can 1 transaction has many _transactionDocumentNumber_ ?
If _transactionDocumentNumber_  is used for assigning, so what  _transactionID_ is used for ?

It seems that I miss the point here.
Hoping you can support me.
Thank you.

*Update: I made some more tests with "re-creating" and "assigning" transactions. It seemed to me that it plays up. It behaves unexpectedly. Sometimes, I can not assign the "re-created" transaction for the customer. I dont know how these functions work. Now I'm totally lost. Is it a bug ?

**Comment by karolbzik** [comment]
@catbuilts in general _transactionID_ is our system ID for this kind of object (Transaction) and it's used only by the system and _transactionDocumentNumber_ is an identifier we are receiving from an external system (eg. ERP, CRM, invoicing system) which can be identified with a transaction, invoice, receipt. _transactionDocumentNumber_ is known and used by a Customer. 

We need to analyze the potential bug with "re-creating" and "assigning", then I will come back to you with the whole explanation. I will come back to you after a few tests.

**Comment by catbuilts** [comment]
Hi @karolbzik 

Are there any updates about  **transactionID** and **transactionDocumentNumber** part ?
Please let me know when the issue is fixed.

Thank you.

**Comment by colejarczyk** [comment]
TransactionID automatically generates an identifier of the transaction in the Open Loyalty. It’s really an internal value without any business meaning, rather technical. You can get transaction details using transaction_id by calling API GET /api/transaction/{transaction}

On the other hand, a document number is strictly business information. Usually, it’s a receipt number or invoice number or any number of a transaction in your system. So when a customer does a return, partial or complete, you send another transaction to the Open Loyalty with type “return” and now Open Loyalty knows how to reduce points from customers account. Here is a scenario:

- A customer made a transaction for 100 euro, one product for 10 euros and second for 90 euros
- A sell transaction was sent to the Open Loyalty with documentNumber “ABC”
- Open Loyalty adds 1000 points for this purchase
- A customer made a return only one product 90 euros
- A return transaction was sent to the Open Loyalty with documentNumber “ABC”
- Open Loyalty calculates proportionally (because earning points rules may change during a time between sell and return) how many points should be reduced from customer’s account. So 100 euros equals 1000 points and 90 euros worth 900 points
- Open Loyalty reduces 900 points from customer’s account.

So a documentNumber is used for returns in the Open Loyalty but also allows to links transactions between systems.
