### ISSUE TITLE
How to customize backend APIs?

### ISSUE THREAD

**Issue by liuzhen2008** [DivanteLtd/open-loyalty#99]
Are the backend api available? Where can we find the code o.O

**Comment by tjurczak** [comment]
Hi @liuzhen2008,

Yes, It is. REST API documentation is available we you go to url on your local machine http://openloyalty.localhost/app_dev.php/doc or http://open-loyalty.readthedocs.io/en/latest/

**Comment by colejarczyk** [comment]
@liuzhen2008 

The Open Loyalty code is in the vendor directory. It's a common practice. You shouldn't modify a code directly because then you won't be able to easily update Open Loyalty to the newest version.

So if you want to change a specific API URL, you need to create a bundle in src directory, register it in AppKernel a then create your own controller. The last thing to do is to override URL settings and point this url to the just created controller.

You can read about it more in the Symfony documentation: https://symfony.com/doc/3.4/bundles/inheritance.html
